bus_app/bus_app/bus_main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name='home'),
    path('apply',views.submit_app_form, name='apply'),
    path('apply-driving-license',views.apply_driving_license, name='apply-driving-license'),
    path('view-application-status',views.view_application, name='view-application-status'),
    path('apply-fitness-certificate',views.apply_fitness_certificate, name='apply-fitness-certificate'),
    path('view-fitness-application-status',views.view_fitness_application, name='view-fitness-application-status'),
]

bus_app/bus_app/dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('',views.index, name='home'),
	
	#license process
	path('learner-applications',views.learner_applications, name='learner-applications'),
	path('learner-details',views.learner_details, name='learner-details'),
	path('approve-learner',views.approve_learner, name='approve-learner'),
	path('approved-for-learner',views.approved_for_learner, name='approved-for-learner'),
	path('mark-ready',views.mark_ready, name='mark-ready'),
	path('ready-for-exam',views.ready_for_exam, name='ready-for-exam'),
	path('mark-setup',views.mark_setup, name='mark-setup'),
	path('submit-marks',views.submit_marks, name='submit-marks'),
	path('failed-in-exam',views.failed_in_exam, name='failed-in-exam'),
	path('passed-in-exam',views.passed_in_exam, name='passed-in-exam'),
	path('applied-for-driving-license',views.applied_for_driving_license, name='applied-for-driving-license'),
	path('issue-driving-license',views.issue_driving_license, name='issue-driving-license'),
	path('issued-driving-license',views.issued_driving_licenses, name='issued-driving-license'),
	
	#fitness renewal
	path('fitness-applications',views.fitness_applications, name='fitness-applications'),
	path('fitness-details',views.fitness_details, name='fitness-details'),
	path('assign-inspector',views.assign_inspector, name='assign-inspector'),
	path('assigned-to-inspector',views.assigned_to_inspector, name='assigned-to-inspector'),
	path('assigned-to-me',views.assigned_to_me, name='assigned-to-me'),
	path('mark-is-inspected',views.mark_as_inspected, name='mark-is-inspected'),
	path('inspected-by-me',views.inspected_by_me, name='inspected-by-me'),
	path('approved-by-inspector',views.approved_by_inspector, name='approved-by-inspector'),
	path('issue-fitness-certificate',views.issue_fitness_certificate, name='issue-fitness-certificate'),
	path('issued-certificates',views.issued_certificates, name='issued-certificates'),
	
	
	#setup
	path('vehicle-type',views.vehicle_type, name='vehicle-type'),
	path('user-setup',views.user_setup, name='user-setup'),
	
	
    path('login',views.login, name='login'),
    path('logout',views.logout, name='logout'),

	#02Feb
	path('brta',views.brta_dashboard, name='brta'),
	path('bus-owner',views.bus_owner_dashboard, name='bus-owner'),
	path('emergency-service',views.emergency_service_dashboard, name='emergency-service'),
	path('urban-authority',views.urban_dashboard, name='urban-authority'),

]

bus_app/bus_app/urls.py
from django.contrib import admin
from django.urls import path, include
import bus_app.bus_main.urls as main_urls
import bus_app.account.urls as account_urls
import bus_app.dashboard.urls as dashboard_urls
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve


#handler404 = 'blog_site.blog_main.views.handle_404'


urlpatterns = [
	path('', include((main_urls, 'bus'), namespace='bus')),
	path('account/', include((account_urls, 'account'), namespace='account')),
	path('dashboard/',include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    path('default-admin-dashboard/', admin.site.urls),
	url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
	url(r'^static/(?P<path>.*)$', serve,{'document_root': "static"}),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root="static")

bus_app/bus_app/bus_main/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.utils.crypto import get_random_string
from datetime import datetime
from .models import LearnerApplication, ExamMarks, DrivingLicense, FitnessApplication, VehicleType
import re



def index(request):
    return redirect('bus:apply')


def submit_app_form(request):
	if request.method=="POST" and request.is_ajax():
		name = request.POST.get("name","").strip()
		contact_no = request.POST.get("contact_no","").strip()
		present_address = request.POST.get("present_address","")
		permanent_address = request.POST.get("permanent_address","")
		national_id = request.POST.get("national_id","").strip()
		tracking_code = get_random_string(length=12)
		if len(name)==0:
			return JsonResponse({'status':4})
		if bool(re.match('^[a-zA-Z- .]+$',name)) == False:
			return JsonResponse({'status':5})
		if len(name)>=66:
			return JsonResponse({'status':6})
		if len(contact_no)==0:
			return JsonResponse({'status':7})
		if len(contact_no)!=11:
			return JsonResponse({'status':8})
		if contact_no[0:2]!="01":
			return JsonResponse({'status':9})
		if bool(re.match('^[0-9]+$',contact_no)) == False:
			return JsonResponse({'status':10})
		if len(permanent_address)==0:
			return JsonResponse({'status':11})
		if len(national_id)==0:
			return JsonResponse({'status':12})
		if bool(re.match('^[0-9]+$',national_id)) == False:
			return JsonResponse({'status':13})
		try:
			an_apply_form = LearnerApplication(name=name, permanent_address=permanent_address,present_address=present_address,
					contact_no=contact_no,tracking_code=tracking_code, national_id=national_id)
			an_apply_form.save()
		except Exception as e:
			print(e)
			return JsonResponse({'status':2})
		try:
			an_apply_form.driver_image = request.FILES['driver_image']
			an_apply_form.nid_image = request.FILES['nid']
			an_apply_form.testimonial = request.FILES['testimonial']
			an_apply_form.apply_form = request.FILES['apply_form']
		except Exception as e:
			print(e)
			return JsonResponse({'status':2})
		an_apply_form.save()
		
		try:
			return JsonResponse({'status':1, 'tracking_id':str(an_apply_form.pk), 'tracking_code':tracking_code})
		except Exception as e:
			return JsonResponse({'status':2})
	return render(request, "bus_main/apply_form.html",{})


def view_application(request):
	if request.method=="GET" and request.is_ajax():		
		try:
			application_id = int(request.GET.get("application",""))
			code = request.GET.get("code","")
			flag_ = request.GET.get("flag","")
			licenseNo = request.GET.get("license_no","")
			learner_application = LearnerApplication.objects.get(pk=application_id, tracking_code=code)
			if flag_=='0' and learner_application.flag>0:
				return JsonResponse({'status':2})
			if flag_=="1":
				learner_application = LearnerApplication.objects.get(pk=application_id, tracking_code=code,license_number=licenseNo)
				if learner_application.flag==6:
					driving_license = DrivingLicense.objects.get(learner_application=learner_application)
					return render(request,"bus_main/application_status.html", {'learner_app':learner_application,'flag':1,
							 'license_no':driving_license.license_no, 'issued_on':driving_license.approve_time})
			return render(request,"bus_main/application_status.html", {'learner_app':learner_application, 'flag':0})
		except Exception as e:
			print(e)
			return JsonResponse({'status':1})
	return render(request, "bus_main/view_learner_application.html",{})


def apply_driving_license(request):
	if request.method=="POST" and request.is_ajax():
		application_id = request.POST.get("application","").strip()
		tracking_code = request.POST.get("code","").strip()
		license_no = request.POST.get("license_no","").strip()
		
		if len(application_id)==0:
			return JsonResponse({'status':4})
		if len(tracking_code)==0:
			return JsonResponse({'status':5})
		if len(license_no)==0:
			return JsonResponse({'status':6})
		try:
			learner_application = LearnerApplication.objects.get(id=application_id, tracking_code=tracking_code, license_number=license_no)
			if learner_application.flag<4:
				return JsonResponse({'status':8})	
		except Exception as e:
			print(e)
			return JsonResponse({'status':7})
		try:
			if DrivingLicense.objects.filter(learner_application=learner_application).count()>0:
				return JsonResponse({'status':9})
			an_apply_form = DrivingLicense(apply_time=datetime.now(),learner_application=learner_application)
			an_apply_form.save()
			learner_application.flag=5
			learner_application.save()
		except Exception as e:
			print(e)
			return JsonResponse({'status':2})
		try:
			an_apply_form.driver_image = request.FILES['driver_image']
			an_apply_form.driver_signature = request.FILES['signature']
			an_apply_form.apply_form = request.FILES['apply_form']
			an_apply_form.learner_license = request.FILES['learner_license']
		except Exception as e:
			print(e)
			return JsonResponse({'status':2})
		an_apply_form.save()
		
		return JsonResponse({'status':1})
	return render(request, "bus_main/apply_driving_license.html",{})


def apply_fitness_certificate(request):
	if request.method=="POST" and request.is_ajax():
		name = request.POST.get("name","").strip()
		contact_no = request.POST.get("contact_no","").strip()
		registration_no = request.POST.get("registration_no","").strip()
		vehicle_type = request.POST.get("vehicle_type","")
		fitness_certi_no = request.POST.get("fitness_certificate_no","")
		tracking_code = get_random_string(length=12)
		tracking_flag = True
		while tracking_flag:
			if FitnessApplication.objects.filter(tracking_code=tracking_code).count()>0:
				tracking_code = get_random_string(length=12)
			else:
				tracking_flag = False
		if len(name)==0:
			return JsonResponse({'status':4})
		if bool(re.match('^[a-zA-Z- .]+$',name)) == False:
			return JsonResponse({'status':5})
		if len(name)>=66:
			return JsonResponse({'status':6})
		if len(contact_no)==0:
			return JsonResponse({'status':7})
		if len(contact_no)!=11:
			return JsonResponse({'status':8})
		if contact_no[0:2]!="01":
			return JsonResponse({'status':9})
		if bool(re.match('^[0-9]+$',contact_no)) == False:
			return JsonResponse({'status':10})
		if len(registration_no)==0:
			return JsonResponse({'status':11})
		if len(vehicle_type)==0:
			return JsonResponse({'status':12})
		if len(fitness_certi_no)==0:
			return JsonResponse({'status':13})

		try:
			an_apply_form = FitnessApplication(name=name, registration_no=registration_no,contact_no=contact_no,fitness_certificate_no=fitness_certi_no,
				tracking_code=tracking_code,apply_time=datetime.now(), vehicle_type=VehicleType.objects.get(id=int(vehicle_type)))
			#an_apply_form.save()
		except Exception as e:
			print(e)
			return JsonResponse({'status':2})
		try:
			an_apply_form.bank_receipt = request.FILES['bank_receipt']
			an_apply_form.fitness_certificate = request.FILES['fitness_certificate']
		except Exception as e:
			print(e)
			return JsonResponse({'status':2})
		an_apply_form.save()
		
		try:
			return JsonResponse({'status':1, 'tracking_id':str(an_apply_form.pk), 'tracking_code':tracking_code})
		except Exception as e:
			return JsonResponse({'status':2})
	
	vehicle_types = VehicleType.objects.all().order_by('name')
	return render(request, "bus_main/apply_fitness_certificate.html",{'vehicle_types':vehicle_types})
	

def view_fitness_application(request):
	if request.method=="GET" and request.is_ajax():		
		try:
			application_id = int(request.GET.get("application",""))
			code = request.GET.get("code","")
			certificateNo = request.GET.get("certificate_no","")
			fitness_application = FitnessApplication.objects.get(pk=application_id, tracking_code=code, fitness_certificate_no=certificateNo)
			
			return render(request,"bus_main/fitness_status.html", {'fitness_app':fitness_application})
		except Exception as e:
			print(e)
			return JsonResponse({'status':1})
	return render(request, "bus_main/view_fitness_application.html",{})

bus_app/templates/bus_main/base.html
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
		<link rel="icon" href="{{static_server}}/img/bus_icon.png" type="image/x-icon"/>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"/>
		<link href="https://fonts.googleapis.com/css?family=Assistant&display=swap" rel="stylesheet"/>
		<link href="https://fonts.googleapis.com/css?family=Open+Sans|Titillium+Web|Ubuntu&display=swap" rel="stylesheet">
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>
		<title>{%block title%}{%endblock%}</title>
		<style>
			*{
				margin:0px;
				padding:0px;
				font-family: 'Assistant', sans-serif;
			}
			
			a, a:hover, a:focus{
				text-decoration:none !important;
			}
			
			::-webkit-scrollbar {
			  width:6px;
			}
			
			::-webkit-scrollbar-track {
				background:rgba(0,0,0,0.1);
			}

			::-webkit-scrollbar-thumb {
			  background:linear-gradient(to right, rgb(52,97,133), rgb(68,126,174));
			  border-radius: 3px;
			}
			
			body{
				min-height:100vh;
				position:relative;				
				/*background-size:cover;
				background-position:center center;
				background:linear-gradient(to top, rgba(37,115,129,0.4), rgba(105,196,211,0.1));*/
				background:url(/static/img/back.png);
				/*background-attachment:fixed;*/
			}
			
			#cu_logo{
				width:50px;				
				margin-top:8px;
				display:inline-block;
			}
			
			#proctor_office_name{
				color:rgb(52,97,133) !important;
				margin-left:14px;
				display:inline-block;
			}
			
			.shadow-with-white{
				background:white;
				padding:20px 40px;
				margin-top:6px;
				border-radius:5px;
				box-shadow:0px 2px 6px 0px rgba(29,108,173,0.4);
			}
			
			.menuHolder{
				/*background:linear-gradient(to right, rgba(0,0,0,0.8), rgba(0,0,0,0.1));
				background:linear-gradient(to right, rgb(37,115,129), rgba(105,196,211,1));
				background:linear-gradient(to right, rgb(217,240,244), rgba(105,196,211,1));
				background:linear-gradient(to left, rgb(238,249,251), rgba(255,255,255,1));*/
				background:white;
				box-shadow:0px 2px 8px 0px rgb(81,129,173);
			}
			
			nav#menu{
				opacity:0px;
			}
								
			#menu ul {
			  margin: 0;
			  padding: 0;
			}

			#menu .main-menu {
			  display: none;
			}

			#tm:checked + .main-menu {
			  display: block;
			}

			#menu input[type="checkbox"],
			#menu ul span.drop-icon {
			  display: none;
			}

			#menu .sub-menu {
			  margin: 0 1em;
			}

			#menu li,
			#toggle-menu,
			#menu a {
			  font-size:13px;
			  position: relative;
			  display: block;
			  color: black;
			  color:rgb(35,102,135);
			  /*text-shadow: 1px 1px 0 rgba(35,102,135,0.1);*/
			}


			#toggle-menu,
			#menu a {
				padding:20px 16px;
			}

			#menu a {
			  transition: all 0.4 ease-in-out;
			  -webkit-transition: all .125s ease-in-out;
			}

			#menu a:hover {
			  background-color: rgba(255,255,255,0.2);
			  background:rgb(238,249,251);
			  border-radius:10px 10px 0px 0px;
			}

			#menu .sub-menu {
			  display: none;
			}

			#menu input[type="checkbox"]:checked + .sub-menu {
			  display: block;
			}

			
			.drop-icon, .drop-icon *{
				color:rgb(36,83,34);
				color:rgb(255,255,255);
				color:rgb(37,117,131);
				cursor:pointer;
			}

			#toggle-menu .drop-icon,
			#menu li label.drop-icon {
			  position: absolute;
			  right: 0;
			  top: 0;
			}
			
			#menu label.drop-icon, #toggle-menu span.drop-icon {
			  padding: 1em;
			  font-size: 1em;
			  text-align: center;
			  text-shadow: 0 0 0 transparent;
			}
			
			.main-menu li a{
				font-size:1.2em !important;
			}
			
			footer{
				width:100%;
				font-size:0.94em;
				text-align:center;
				padding:12px;
				background:linear-gradient(to bottom, rgb(255,255,255), rgba(35,133,150,0.1));
				box-shadow:0px -2px 10px 0px rgba(48,97,146,0.2);
				position:absolute;
				bottom:0px;
			}
			
			footer h6{
				color:rgb(36,92,150);
			}
			
			#mdd{
				color:rgb(48,87,146);
				font-family:'Ubuntu', 'Titillium Web', verdana;
				font-size:1.02em;
				transition:all 0.5s;
			}
			
			#mdd:hover{
				color:rgb(70,143,169);
			}
			
			.top_app_name{
				color:rgb(52,97,133) !important;
				/*font-weight:bold;*/
			}
			
			@media only screen and (max-width: 1023px) {
				#proctor_office_name{
					font-size:0.82em !important;
				}
				.top_app_name{
					font-size:1.1em;
				}
				#menu a {
					padding:12px 8px;
				}
				.main-menu li a{
					font-size:1.14em !important;
				}
			}
			
			@media only screen and (max-width: 768px) {
				#proctor_office_name{
					font-size:0.65em !important;
				}
				#cu_logo{
					width:35px;
				}
				.main-menu li a{
					font-size:1.08em !important;
				}
			}
			
			.proctor_table{
				cursor:pointer;
			}
			
			@media only screen and (min-width: 1024px) {
			  #menu .main-menu {
				display: block;
			  }

			  #toggle-menu,
			  #menu label.drop-icon {
				display: none;
			  }

			  #menu ul span.drop-icon {
				display: inline-block;
			  }

			  #menu li {
				float: left;
				border-width: 0 1px 0 0;
			  }

			  #menu .sub-menu li {
				float: none;
			  }

			  #menu .sub-menu {
				border-width: 0;
				margin: 0;
				position: absolute;
				top: 100%;
				left: 0;
				width: 12em;
				z-index: 3000;
			  }

			  #menu .sub-menu,
			  #menu input[type="checkbox"]:checked + .sub-menu {
				display: none;
			  }

			  #menu .sub-menu li {
				border-width: 0 0 1px;
			  }

			  #menu .sub-menu .sub-menu {
				top: 0;
				left: 100%;
			  }

			 #menu .sub-menu .drop-icon {
				position: absolute;
				top: 0;
				right: 0;
				padding: 1em;
			  }

			  #menu li:hover > input[type="checkbox"] + .sub-menu {
				display: block;
			  }
			 }
			 .vc_message{
				background:white;
				padding:6px 8px;
				border:solid 1px rgba(52,97,133,0.3);
				box-shadow:0px 2px 4px 0px rgb(52,97,133);
				border-radius:0px 6px 6px 0px;
				display:inline-block;
				position:fixed;
				left:-113px;
				opacity:0;
				transition:all 1s;
				cursor:pointer;
				z-index:999999;
			 }
			 .vc_message:hover{
				left:0px;
			 }
			 .vc_message td{
				color:rgb(52,97,133);
				font-size:1em;
				font-weight:bold;
				text-align:center;
			 }
			 .vc_message_viewer{
				width:450px;
				height:70vh;
				background:white;
				border-radius:3px;
				padding:12px;
				box-shadow:0px 2px 4px 0px rgb(52,97,133);
				position:fixed;
				overflow-y:scroll;
				top:15vh;
				z-index:999999;
				opacity:0;
			 }
			 @keyframes toLeft{
				0%{left:0px;}
				100%{left:-113px;}
			 }
			 @keyframes toRight{
				0%{left:-113px;}
				100%{left:0px;}				
			 }
			 .vc_image{
				width:40%;
				margin-left:30%;
				border-radius:50%;
				box-shadow:0px 2px 4px 0px rgb(52,97,133);
			 }
			 .vc_name{
				color:rgb(52,97,133);
				margin-top:10px;
				text-align:center;
			 }
		</style>
		{% block style %}{% endblock %}
	</head>
	
	<body>
		<div class="container-fluid menuHolder">
			<div class="row">
				<div class="col-lg-3 col-md-12 col-sm-12">
					
				</div>				
				<div class="col-lg-6 col-md-12 col-sm-12">
					<div class="text-center" style="margin-top:4px;">
						<h4 class="top_app_name">
							Nirapod Bus App
						</h4>
					</div>
				</div>
					<div class="col-lg-3 col-md-12 col-sm-12">
						<div class="text-right" style="margin-top:4px;">
							{% if request.user.is_authenticated %}
								<a href="{% url 'dashboard:home' %}" style="color:rgb(52,97,133);font-size:0.95em;">
									<i class="fa fa-tachometer"></i> &nbsp;Dashboard
								</a>
								&nbsp;&nbsp;&nbsp;
								<a href="{% url 'dashboard:logout' %}" style="color:rgb(52,97,133);font-size:0.95em;">
									<i class="fa fa-power-off"></i> &nbsp;Logout
								</a>
							{% else %}
								<a href="{% url 'dashboard:login' %}" style="color:rgb(52,97,133);font-size:0.95em;">
									<i class="fa fa-user"></i> &nbsp;Login
								</a>
							{% endif %}
						</div>
					</div>
				<div class="col-lg-12 col-md-12 col-sm-12">
					<nav id="menu" class="cf lab-nav lab-nav--light">
						<label for="tm" id="toggle-menu">
							<span class="drop-icon" style="font-size:1.3em;margin:5px;padding:5px;">
								<i class="fa fa-bars"></i>
							</span>
						</label>
					  <input type="checkbox" id="tm">
						  <ul class="main-menu cf">
								<li>
									<a href="{% url 'bus:apply' %}">
										<i class="fa fa-file-text-o"></i> &nbsp;Apply for Learner License
									</a>
								</li>
								<li>
									<a href="{% url 'bus:view-application-status' %}">
										<i class="fa fa-list-alt"></i> &nbsp;Check License Application Status
									</a>
								</li>
								<li>
									<a href="{% url 'bus:apply-driving-license' %}">
										<i class="fa fa-id-card-o"></i> &nbsp;Apply for Driving License
									</a>
								</li>
								<li>
									<a href="{% url 'bus:apply-fitness-certificate' %}">
										<i class="fa fa-id-card"></i> &nbsp;Apply for Fitness Certicate
									</a>
								</li>
								<li>
									<a href="{% url 'bus:view-fitness-application-status' %}">
										<i class="fa fa-list-alt"></i> &nbsp;Check Fitness Application Status
									</a>
								</li>
						  </ul>
					</nav>
				</div>
			</div>
		</div>
			
		<br/><br/>
		
		{% block content %}{% endblock %}
		
		<br/><br/><br/><br/><br/>
		<footer style="display:none;">
			<h6 style="text-align:right;">Developed by 
				<a href="http://middaydreams.co.uk?a=p" target="_blank" title="Quality, Innovation, Social Business"><span id="mdd" style="color:rgb(13,40,70);">MidDayDreams</span></a>
			</h6>
		</footer>
	 
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
	
		<script>
		
			var isMobile = false;			
			if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|ipad|iris|kindle|Android|Silk|lge |maemo|midp|mmp|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows (ce|phone)|xda|xiino/i.test(navigator.userAgent) 
				|| /1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(navigator.userAgent.substr(0,4))) { 
				isMobile = true;
			}
			
			function setUpMenu(){
				if(window.innerWidth>1023 && !isMobile){
					var menuWidth = 0;
					$("ul.cf").children("li").each(function(){
						menuWidth += $(this).outerWidth();
					});
					$("ul.cf").css("margin-left",(window.innerWidth-menuWidth)/2-32);
					$(".vc_message").css({
						"top":(window.innerHeight-$(".vc_message").outerHeight())/2,
						"opacity":1
					});
				}else{
					$("ul.cf").css("margin-left","0");
					$(".vc_message").css({
						"top":(window.innerHeight-$(".vc_message").outerHeight())/2,
						"opacity":0
					});
				}
				$(".vc_image").height($(".vc_image").width());
				$(".vc_message_viewer").css({
					"opacity":"1",
					"display":"none"
				});
				$("nav#menu").css("opacity","1");		
			}
			
			var slided = false;
			
			$(document).ready(function(){
			
				setUpMenu();
				
				$(".vc_message_viewer").css("left",($(".vc_message").outerWidth()+4));
				
				$(".vc_message").click(function(){
					if(!slided){
						$(".vc_message").css("left","0px");
						$(".vc_message_viewer").slideDown(600, function(){
							slided = true;
						});						
					}else{
						$(".vc_message").css("left","");
						$(".vc_message_viewer").slideUp(400, function(){
							slided = false;
						});
					}
				});
				
				
			});
			
			$(window).resize(function(){
				setUpMenu();
			});
		
		</script>	
	{% block script %}{% endblock %}
	</body>
</html>