bus_app/bus_app/dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('',views.index, name='home'),
	
	#license process
	path('learner-applications',views.learner_applications, name='learner-applications'),
	path('learner-details',views.learner_details, name='learner-details'),
	path('approve-learner',views.approve_learner, name='approve-learner'),
	path('approved-for-learner',views.approved_for_learner, name='approved-for-learner'),
	path('mark-ready',views.mark_ready, name='mark-ready'),
	path('ready-for-exam',views.ready_for_exam, name='ready-for-exam'),
	path('mark-setup',views.mark_setup, name='mark-setup'),
	path('submit-marks',views.submit_marks, name='submit-marks'),
	path('failed-in-exam',views.failed_in_exam, name='failed-in-exam'),
	path('passed-in-exam',views.passed_in_exam, name='passed-in-exam'),
	path('applied-for-driving-license',views.applied_for_driving_license, name='applied-for-driving-license'),
	path('issue-driving-license',views.issue_driving_license, name='issue-driving-license'),
	path('issued-driving-license',views.issued_driving_licenses, name='issued-driving-license'),
	
	#fitness renewal
	path('fitness-applications',views.fitness_applications, name='fitness-applications'),
	path('fitness-details',views.fitness_details, name='fitness-details'),
	path('assign-inspector',views.assign_inspector, name='assign-inspector'),
	path('assigned-to-inspector',views.assigned_to_inspector, name='assigned-to-inspector'),
	path('assigned-to-me',views.assigned_to_me, name='assigned-to-me'),
	path('mark-is-inspected',views.mark_as_inspected, name='mark-is-inspected'),
	path('inspected-by-me',views.inspected_by_me, name='inspected-by-me'),
	path('approved-by-inspector',views.approved_by_inspector, name='approved-by-inspector'),
	path('issue-fitness-certificate',views.issue_fitness_certificate, name='issue-fitness-certificate'),
	path('issued-certificates',views.issued_certificates, name='issued-certificates'),
	
	
	#setup
	path('vehicle-type',views.vehicle_type, name='vehicle-type'),
	path('user-setup',views.user_setup, name='user-setup'),
	
	
    path('login',views.login, name='login'),
    path('logout',views.logout, name='logout'),

	#02Feb
	path('brta',views.brta_dashboard, name='brta'),
	path('bus-owner',views.bus_owner_dashboard, name='bus-owner'),
	path('emergency-service',views.emergency_service_dashboard, name='emergency-service'),
	path('urban-authority',views.urban_dashboard, name='urban-authority'),

]

bus_app/bus_app/urls.py
from django.contrib import admin
from django.urls import path, include
import bus_app.bus_main.urls as main_urls
import bus_app.account.urls as account_urls
import bus_app.dashboard.urls as dashboard_urls
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.static import serve


#handler404 = 'blog_site.blog_main.views.handle_404'


urlpatterns = [
	path('', include((main_urls, 'bus'), namespace='bus')),
	path('account/', include((account_urls, 'account'), namespace='account')),
	path('dashboard/',include((dashboard_urls, 'dashboard'), namespace='dashboard')),
    path('default-admin-dashboard/', admin.site.urls),
	url(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
	url(r'^static/(?P<path>.*)$', serve,{'document_root': "static"}),
]

urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root="static")

bus_app/bus_app/dashboard/models.py
from django.db import models

# Create your models here.

bus_app/bus_app/dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth
from django.http import JsonResponse
from django.core.paginator import Paginator
from datetime import datetime
from django.db.models import Max
from ..decorators import login_required, superuser_required
from ..account.models import AppUser
from ..bus_main.models import LearnerApplication, MinimumMarks, ExamMarks, VehicleType, DrivingLicense, FitnessApplication
import re

def login(request):
    if request.user.is_authenticated:
        return redirect('dashboard:home')
    if request.is_ajax() and request.method == "POST":
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")
        if len(username) == 0:
            return JsonResponse({'status':0})
        elif len(password) == 0:
            return JsonResponse({'status':2})
        else:
            user = auth.authenticate(username=username.lower(), password=password)
            if user is not None:
                auth.login(request, user)
                return JsonResponse({'status':1})
    return render(request,'dashboard/login.html')



#@superuser_required
def index(request):
    if not request.user.is_authenticated:
        return redirect('bus:home')
    
    context = {}
    if request.user.is_superuser:
        context.update({
            'learner_applications':str(LearnerApplication.objects.filter(flag=0).count()),
            'approved_for_learner':str(LearnerApplication.objects.filter(flag=1).count()),
            'ready_for_exam':str(LearnerApplication.objects.filter(flag=2).count()),
            'passed_in_exam':str(LearnerApplication.objects.filter(flag=4).count()),
            'applied_for_driving_license':str(LearnerApplication.objects.filter(flag=5).count()),
            'issued_licenses':str(LearnerApplication.objects.filter(flag=6).count()),
            'fitness_applications':str(FitnessApplication.objects.filter(flag=0).count()),
            'approved_by_inspectors':str(FitnessApplication.objects.filter(flag=2).count()),
            'issued_certificates':str(FitnessApplication.objects.filter(flag=3).count()),
        })
    else:
        context.update({
            'assigned_to_me':str(FitnessApplication.objects.filter(flag=1,inspected_by=request.user).count()),
            'approved_by_me':str(FitnessApplication.objects.filter(flag__gte=2,inspected_by=request.user).count()),
        })
    return render(request,'dashboard/index.html', context)


@superuser_required
def learner_applications(request):
    try:
        learner_applications = Paginator(LearnerApplication.objects.filter(flag=0).order_by('apply_time'),20).page(request.GET.get("page",1))
        return render(request,'dashboard/learner_applications.html', {'learner_applications':learner_applications})
    except Exception as e:
        print(e)
        return redirect('dashboard:home')



@superuser_required
def learner_details(request):
    if request.is_ajax():
        try:
            an_application = LearnerApplication.objects.get(id=int(request.GET.get("learner_id","")))
            context = {
                'an_application':an_application
            }
            if 'view_exam_history' in request.GET:
                context.update({
                    'view_exam_history':True
                })
            if an_application.flag>=5:
                try:
                    driving_application = DrivingLicense.objects.get(learner_application=an_application)
                    context.update({
                        'driving_application':driving_application
                    })
                except Exception as e:
                    print(e)
            return render(request,'dashboard/learner_details.html', context)
        except Exception as e:
            print(e)
    return redirect('dashboard:home')



@superuser_required
def approve_learner(request):
    if request.is_ajax():
        try:
            an_application = LearnerApplication.objects.get(id=int(request.POST.get("learner_id","")))
            if an_application.flag==0:
                an_application.flag = 1
                max_license_number = LearnerApplication.objects.aggregate(Max('license_number'))['license_number__max']
                if max_license_number==0:
                    an_application.license_number = 1000000
                else:
                    an_application.license_number = max_license_number+1
                an_application.approve_time = datetime.now()
                an_application.approved_by = request.user
                an_application.save()
            return JsonResponse({'status':1})
        except Exception as e:
            print(e)
            return JsonResponse({'status':0})
    return redirect('dashboard:home')


@superuser_required
def approved_for_learner(request):
    try:
        learner_applications = Paginator(LearnerApplication.objects.filter(flag=1).order_by('apply_time'),20).page(request.GET.get("page",1))
        return render(request,'dashboard/approved-for-learner.html', {'learner_applications':learner_applications})
    except Exception as e:
        print(e)
        return redirect('dashboard:home')


@superuser_required
def mark_ready(request):
    if request.is_ajax():
        try:
            an_application = LearnerApplication.objects.get(id=int(request.POST.get("learner_id","")))
            if an_application.flag==1:
                an_application.flag = 2
                an_application.ready_time = datetime.now()
                an_application.marked_ready_by = request.user
                an_application.save()
            return JsonResponse({'status':1})
        except Exception as e:
            print(e)
            return JsonResponse({'status':0})
    return redirect('dashboard:home')


@superuser_required
def ready_for_exam(request):
    try:
        learner_applications = Paginator(LearnerApplication.objects.filter(flag=2).order_by('apply_time'),20).page(request.GET.get("page",1))
        return render(request,'dashboard/ready-for-exam.html', {'learner_applications':learner_applications})
    except Exception as e:
        print(e)
        return redirect('dashboard:home')


import math
def mark_setup(request):
        minimum_marks = MinimumMarks.objects.first()
        if request.is_ajax() and request.method=="POST":
            try:
                written_marks = float(request.POST.get("written_marks", ""))
                field_test_marks = float(request.POST.get("field_test_marks", ""))
                viva_marks = float(request.POST.get("viva_marks", ""))
                if math.ceil(written_marks)==0 or math.ceil(field_test_marks)==0 or math.ceil(viva_marks)==0:
                    return JsonResponse({'status':0})
            except Exception as e:
                print(e)
                return JsonResponse({'status':0})
            if MinimumMarks.objects.all().count()>0:
                MinimumMarks.objects.update(written_marks=written_marks, field_test_marks=field_test_marks, viva_marks=viva_marks, entry_time=datetime.now(), entry_by=request.user)
            else:
                MinimumMarks(written_marks=written_marks, field_test_marks=field_test_marks, viva_marks=viva_marks, entry_time=datetime.now(), entry_by=request.user).save()
            return JsonResponse({'status':1})
        return render(request,'dashboard/mark-setup.html', {'minimum_marks':minimum_marks})



@superuser_required
def submit_marks(request):
    if request.is_ajax():
        try:
            if MinimumMarks.objects.all().count()==0:
                return JsonResponse({'status':4})
            an_application = LearnerApplication.objects.get(id=int(request.POST.get("learner_id","")))
            if an_application.flag<2:
                return JsonResponse({'status':3})
            if an_application.flag>=4:
                return JsonResponse({'status':5})
            written_marks = request.POST.get("written_marks", "")
            written_exam_date = request.POST.get("written_date", "")
            field_test_marks = request.POST.get("field_test_marks", "")
            field_test_date = request.POST.get("field_test_date", "")
            viva_marks = request.POST.get("viva_marks", "")
            viva_exam_date = request.POST.get("viva_date", "")
            if len(written_marks)==0 or len(written_exam_date)==0 or len(field_test_marks)==0 or len(field_test_date)==0 or len(viva_marks)==0 or len(viva_exam_date)==0:
                return JsonResponse({'status':0})   
            exam_marks = ExamMarks(written_marks=written_marks, written_exam_date=written_exam_date, field_test_marks=field_test_marks, field_test_date=field_test_date, viva_marks=viva_marks, viva_exam_date=viva_exam_date, entry_time=datetime.now(), entry_by=request.user, learner_application=an_application)
            minimum_marks = MinimumMarks.objects.first()
            if float(written_marks)<minimum_marks.written_marks or float(field_test_marks)<minimum_marks.field_test_marks or float(viva_marks)<minimum_marks.viva_marks:
                an_application.flag = 3
                exam_marks.has_passed = False
            else:
                an_application.flag = 4
                exam_marks.has_passed = True
            exam_marks.save()
            an_application.save()
            return JsonResponse({'status':1, 'has_passed':exam_marks.has_passed})
        except Exception as e:
            print(e)
            return JsonResponse({'status':0})
    return redirect('dashboard:home')


@superuser_required
def failed_in_exam(request):
    try:
        learner_applications = Paginator(LearnerApplication.objects.filter(flag=3).order_by('apply_time'),20).page(request.GET.get("page",1))
        return render(request,'dashboard/failed-in-exam.html', {'learner_applications':learner_applications})
    except Exception as e:
        print(e)
        return redirect('dashboard:home')

bus_app/templates/dashboard/assigned-to-me.html
{% extends "dashboard/dashboard.html" %}

{% block title %}
	Fitness Renewal Applications Assigned to Me
{% endblock %}

{% block style%}

	<style>
	
		.view_learner_button{
			color:white;
			font-size:0.9em;
			background:linear-gradient(to right, rgb(39,175,190), rgb(39,98,143)) !important;
			padding:4px 16px;
		}
		
		label[for="inspector"], label[for="inspection_date"], label[for="remarks"]{
			font-family:'Titillium Web' !important;
			font-size:1.5em !important;
			margin-bottom:4px;
		}
		
		select#inspector, select#inspection_date, #remarks{
			font-size:1.2em;
		}
		
		.modal-title{
			font-size:1.8em;
		}
		
		.learner_point, .learner_description{
			margin:0px;			
			padding:0px;
		}
		
		.learner_point{
			font-size:1.2em;
			font-weight:bold;
			margin-top:6px;
		}
		
		.learner_description{
			font-size:1.14em;
		}
		
		.inspector_button, .inspector_button:hover, .inspector_button:focus{
			color:white;
			background:linear-gradient(to right, rgb(39,175,190), rgb(39,98,143)) !important;
		}
		
		.modal_close_button, .modal_close_button:hover, .modal_close_button:focus{
			color:rgb(35,112,169);
			background:linear-gradient(to bottom, rgb(232,160,108), rgb(221,37,11)) !important;
			background:linear-gradient(to bottom, rgb(255,255,255), rgb(204,226,244)) !important;
		}
		
		table.dataTable{
			margin-top:0px !important;
		}
		
		table.dataTable thead .sorting:after, table.dataTable thead .sorting_asc:after,
			table.dataTable thead .sorting_asc_disabled:after, table.dataTable thead .sorting_desc:after,
				table.dataTable thead .sorting_desc_disabled:after,
		table.dataTable thead .sorting:before, table.dataTable thead .sorting_asc:before,
			table.dataTable thead .sorting_asc_disabled:before, table.dataTable thead .sorting_desc:before,
				table.dataTable thead .sorting_desc_disabled:before{
					content:"";
		}
		
		#for_datatable_info{
			opacity:0;
		}
		
		#for_datatable_wrapper .row{
			width:100% !important;
		}
		
		#for_datatable_wrapper .row, #for_datatable_wrapper .col-sm-12{
			margin:0px;
			padding:0px;
		}
		
		.searcher_table{
			width:100%;
		}
		
		.media_holder{
			margin-top:20px;
			padding:8px 15px 0px 15px;
			box-shadow:0px 2px 6px 0px rgb(172,210,238);
		}
				
		#view_nid_image, #view_testimonial, #view_apply_form,
			#download_nid_image, #download_testimonial, #download_apply_form{
				color:white;
				background:linear-gradient(to right, rgb(39,175,190), rgb(39,98,143)) !important;
		}
		
		.extra_space{
			height:2px;
			margin:0px;
			padding:0px;
		}
		
		#nid_image, #testimonial, #apply_form{
			width:60%;
			margin-top:10px;
			margin-bottom:12px;
			box-shadow:0px 2px 6px 0px rgb(172,210,238);
			border-radius:4px;
			display:none;			
		}
		
		.approval_div{
			font-size:1.3em;			
			padding:10px;
			box-shadow:0px 2px 6px 0px rgb(172,210,238);
		}
		
		.approval_div .fas{
			color:rgb(72,184,18);
			font-size:1.2em;
		}
		
		.approval_div .fa-id-badge{
			color:rgb(58,169,213);
		}
		
		.approval_div span{
			font-size:1em;
			font-weight:bold;
		}
		
		#inspection_date{
			color:black !important;
			background:white !important;
			border:solid 1px rgb(126,182,237) !important;
		}
		
		/*
			screen media
		*/
		
		@media only screen and (max-width: 992px) {
			.media_holder{
				padding:6px;
			}
			#nid_image, #testimonial, #apply_form{
				width:100%;
			}
		}
				
	</style>
	
{% endblock %}

{% block maincontent %}
	<div class="list_div">
		<div class="title_holder">						
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12">
					<h1 class="menu_heading">Fitness Renewal Applications Assigned to Me</h1>
				</div>
			</div>
			<br/>
		</div>
		<div class="container-fluid">					
			<div class="row">
				<div class="col-lg-12 col-md-12 col-sm-12">
					<input type="text" id="search_box" class="form-control" placeholder="search here..."/>
					<div class="list_container">
						<table class="table table-hover table-striped category_table searcher_table" id="for_datatable">
							<thead>
								<tr>
									<th>
										Name and Contact
									</th>
									<th class="not-mobile">
										Vehicle Type
									</th>
									<th class="not-mobile">
										Registration No.
									</th>
									<th class="not-mobile">
										Time of Application
									</th>
									<th>
										Actions
									</th>
								</tr>
							</thead>
							<tbody>
								{% for an_application in fitness_applications %}
									<tr data-fitness_id="{{an_application.id}}">
										<td>
											{{an_application.name}}<br/>
											({{an_application.contact_no}})
										</td>
										<td>
											{{an_application.vehicle_type.name}}
										</td>
										<td>
											{{an_application.registration_no}}
										</td>
										<td>
											{{an_application.apply_time}}
										</td>
										<td>
											<button class="btn view_learner_button" data-fitness_id="{{an_application.id}}" data-toggle="modal" data-target="#learnerModal">
												View
											</button>
										</td>
									</tr>
								{% endfor %}								
							</tbody>
						</table>
					</div>								
				</div>
				<div class="col-lg-12">
					{% if fitness_applications.has_other_pages %}
						<br/>
						<div style="position:relative;">
							<ul class="pagination" style="position:absolute;right:0px;">
								{% if fitness_applications.has_previous %}
									<li class="page-item">
										<a class="page-link
											{% if from_type %}
												food-link
											{% else %}
												cat-link
											{% endif %}"
										href="?page={{fitness_applications.previous_page_number}}" tabindex="-1">
											&laquo;
										</a>
									</li>
								{% endif %}                                 
								{% for i in fitness_applications.paginator.page_range %}
									{% if fitness_applications.number == i %}
										<li class="page-item">
											<a class="page-link
											{% if from_type %}
												food-link
											{% else %}
												cat-link
											{% endif %}
										 active" href="#">{{i}} <span class="sr-only">(current)</span></a>
										</li>
									{% else %}
											<li class="page-item">
												<a class="page-link 
													{% if from_type %}
														food-link
													{% else %}
														cat-link
													{% endif %}" href="?page={{i}}">
													{{i}}
												</a>
											</li>
									{% endif %}
								{% endfor %}
								{% if fitness_applications.has_next %}
									<li class="page-item">
										<a class="page-link 
											{% if from_type %}
												food-link
											{% else %}
												cat-link
											{% endif %}" href="?page={{fitness_applications.next_page_number}}" tabindex="-1">
											&raquo;
										</a>
									</li>
								{% endif %}
							</ul>
						</div>
					{% endif %}
					<br/><br/><br/><br/>
				</div>
			</div>
		</div>					
	</div>
	
	<div class="modal fade" id="learnerModal">
		<div class="modal-dialog modal-lg">
		  <div class="modal-content" id="modal_content">
				<div class="modal-header">
				  <h4 class="modal-title menu_heading">&nbsp;</h4>
				  <button type="button" class="close" data-dismiss="modal">&times;</button>
				</div>
				
				<div class="modal-body">
				  &nbsp;
				</div>
				
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary modal_close_button" data-dismiss="modal">Close</button>
				</div>
		  </div>
		</div>
	  </div>

{% endblock %}

{% block script %}
	
	<script>
		
		function showMessage(message){
				$(".showMessage").css("animation","none");
				setTimeout(function(){
					$(".showMessage").html(message)
					.css("animation","animateMessage 6s forwards");
				},100);
		}
				
		$.fn.extend({
			filters: function (table) {
				var box = $(this);
				$(this).keyup(function () {
					var searchText = $.trim($(box).val()).toLowerCase();
					$(table + " tbody tr").each(function () {
						$(this).css("display", $(this).text().toLowerCase().indexOf(searchText) === -1 ? "none" : "");
					});
				});
				return $(this);
			}
		});
		
		var sliding = false;
		
		$(document).ready(function(){
		
			$('.nav-item[data-menu="assigned-to-me"]').addClass("active");
			$('.nav-item[data-slide="inspector-menu"]').show();
			var activated_data = $('.nav-item[data-menu="assigned-to-me"]').data("slide");
			$(".fa[data-icon='"+activated_data+"']").removeClass("fa-plus-circle").addClass("fa-minus-circle");

			$("#search_box").filters(".searcher_table");
			
			$("#inspection_date").datepicker();
			
			$("#for_datatable").DataTable({
			  paging:false,
			  searching:false,
			  responsive:true,
			  sorting:false,
			  bDestroy: true,
			  columnDefs: [
				{ responsivePriority: 1, targets: 0 },
				{ responsivePriority: 2, targets: -1 },
				]
			});
			
			$(document).on("click", "#view_nid_image, #view_testimonial, #view_apply_form", function(){
				if(sliding){
					return;
				}
				sliding = true;
				var slided = $(this).data("slided");
				$(this).data("slided", !slided);
				if(slided){
					$(this).html("View");
					$(this).siblings("img").slideUp(400, function(){
						sliding = false;
					});
				}else{
					$(this).html("Hide");
					$(this).siblings("img").slideDown(500, function(){
						sliding = false;
					});
				}				
			});
			
			$(document).on("click", ".inspector_button", function(){
				var fitness_id = $.trim($(this).data("fitness_id"));
				var fitness_name = $(this).data("fitness_name");
				var inspection_date = $.trim($("#inspection_date").val());
				var remarks = $.trim($("#remarks").val());
				
				if(inspection_date.length==0){
					showMessage("Please Insert Inspection Date");
					return;
				}
								
				$.confirm({
					theme:'material',
					animation:'news',
					closeAnimation: 'rotateX',
					title: 'Mark as Inspected?',
					content: 'Do You Want to Mark Fitness Renewal Application by <b>'+fitness_name+'</b> as Inspected?',
					buttons: {
						confirm:{
							text: 'Yes',
							btnClass: 'btn-yes',
							keys: ['enter', 'shift'],
							action: function(){								
								$.ajax({
									url:"{% url 'dashboard:mark-is-inspected' %}",
									method:"POST",
									data:{fitness_id:fitness_id,inspection_date:inspection_date,remarks:remarks,csrfmiddlewaretoken:"{{csrf_token}}"},
									success:function(data){
										if(data.status==1){
											showMessage('Fitness Renewal Application by '+fitness_name+' has been Marked as Inspected');
											$(".modal_close_button").trigger("click");
											$('tr[data-fitness_id="'+fitness_id+'"]').remove();
										}else{
											showMessage("Sorry, an error occured");
										}
									},
									error:function(error){
										showMessage("Sorry, an error occured");
									}
								});								
							}
						},
						cancel:{
							text: 'No',
							btnClass: 'btn-no',
							keys: ['esc'],
							action:function(){}
						}
					}
				});
				
			});
			
			$(document).on("click", "#download_nid_image, #download_testimonial, #download_apply_form", function(){
				var image_source = $(this).data("source");
				window.open(image_source, '_blank').focus();
			});
			
			$(document).on("click", ".view_learner_button" , function(){
				var fitness_id = $(this).data("fitness_id");
				$(".modal-title, .modal-body").html("Loading...");
				$.ajax({
					url:"{% url 'dashboard:fitness-details' %}",
					method:"GET",
					data:{fitness_id:fitness_id},
					success:function(data){
						$("#modal_content").html(data);
						setTimeout(function(){
							$("#inspection_date").datepicker({
								dateFormat: "yy-mm-dd",
								changeYear: true,
								changeMonth: true,
							}).datepicker("setDate", new Date());
						},500);						
					},
					error:function(error){
						showMessage("Sorry, an error occured");
					}
				})
				
			});
					
		});
		
	
	</script>
	
{% endblock %}